DELETED_PREFIX = "###__md_deleted__###"

# ERROR CODES
NOT_MDM_REPOSITORY = 100
CANT_CREATE_SQLITE_SESSION = 101
CANT_LOAD_CONFIGURATION = 102
AMBIGUOUS_REPOSITORY = 103
PATH_NOT_WITHIN_REPOSITORY = 104
MISSING_RECURSIVE_FLAG = 105
